name: auto-release

on:
  push:
    branches:
    - master

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    # Drafts your next Release notes as Pull Requests are merged into "master"
    - name: Harden Runner
      uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: release-drafter/release-drafter@cfc5540ebc9d65a8731f02032e3d44db5e449fb6 # v5.22.0
      with:
        publish: false
        prerelease: false
        config-name: auto-release.yml
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
