name: chatops
on:
  issue_comment:
    types: [created]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - name: "Handle common commands"
        uses: cloudposse/actions/github/slash-command-dispatch@45e16b2683a6ebe0625b6ca322858354b83443ab # 0.30.0
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: cloudposse/actions
          commands: rebuild-readme, terraform-fmt
          permission: triage
          issue-type: pull-request

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: "Checkout commit"
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - name: "Run tests"
        uses: cloudposse/actions/github/slash-command-dispatch@45e16b2683a6ebe0625b6ca322858354b83443ab # 0.30.0
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: cloudposse/actions
          commands: test
          permission: triage
          issue-type: pull-request
          reactions: false


